#!/usr/bin/env python3
"""System-wide ALSA dsnoop/dmix configuration for shared wakeword/STT audio.

This script is intended to be run with sudo on the target device.

It will:
- Inspect `arecord -l` to discover the USB microphone card index
- Write /etc/asound.conf with a dsnoop capture device at 16 kHz
- Expose a shared `smartcar` PCM that services open via the ALSA `default` device

After running this script, services should set their mic device to
`default` so PyAudio talks to the shared dsnoop layer instead of the
raw hardware.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


CARD_LINE = re.compile(r"card (\d+): ([^\[]+)\[([^\]]+)\], device (\d+): ([^\[]+)\[([^\]]+)\]")


@dataclass
class ALSADevice:
    card: int
    device: int
    name: str


def _run_cmd(cmd: list[str]) -> str:
    proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise RuntimeError(f"Command {' '.join(cmd)} failed: {proc.stderr.strip()}")
    return proc.stdout


def _find_capture_device(keyword: str) -> ALSADevice:
    out = _run_cmd(["arecord", "-l"])
    keyword_lower = keyword.lower()
    for line in out.splitlines():
        m = CARD_LINE.search(line)
        if not m:
            continue
        card = int(m.group(1))
        device = int(m.group(4))
        long_name = m.group(3).strip()
        if keyword_lower in long_name.lower():
            return ALSADevice(card=card, device=device, name=long_name)
    raise SystemExit(f"Could not locate capture device containing '{keyword}' in arecord -l output")


def _render_asound_conf(capture: ALSADevice, *, capture_rate: int, playback_card: int = 0, playback_device: int = 0) -> str:
    """Render a conservative system-wide dsnoop/dmix config.

    - `smartcar_capture` is a dsnoop device on the USB mic at 16 kHz mono
    - `smartcar_playback` is a simple plug to the given playback device
    - `smartcar` is an asym wrapper used as the system `default` PCM
    """

    return f"""
# Auto-generated by tools/fix_audio_config.py
# Capture: card {capture.card}, device {capture.device}, name={capture.name}

pcm.smartcar_capture {{
    type dsnoop
    ipc_key 2048
    ipc_key_add_uid true
    slave {{
        pcm "hw:{capture.card},{capture.device}"
        channels 1
        rate {capture_rate}
        format S16_LE
    }}
}}

pcm.smartcar_playback {{
    type dmix
    ipc_key 2049
    ipc_key_add_uid true
    slave {{
        pcm "hw:{playback_card},{playback_device}"
        channels 2
        rate 48000
        format S16_LE
    }}
}}

pcm.smartcar {{
    type asym
    playback.pcm "smartcar_playback"
    capture.pcm "smartcar_capture"
}}

pcm.!default pcm.smartcar
ctl.!default {{
    type hw
    card {playback_card}
}}
""".lstrip()


def write_asound_conf(content: str, path: Path = Path("/etc/asound.conf")) -> Path:
    if path.exists():
        backup = path.with_suffix(path.suffix + ".backup")
        path.replace(backup)
        print(f"Existing {path} backed up to {backup}")
    path.write_text(content)
    print(f"Wrote ALSA configuration to {path}")
    return path


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate /etc/asound.conf with dsnoop/dmix devices")
    parser.add_argument("--keyword", default="USB Audio", help="Substring to match for the USB microphone in arecord -l")
    parser.add_argument("--capture-rate", type=int, default=16000, help="Capture sample rate for dsnoop (Hz; must stay 16000)")
    parser.add_argument("--playback-card", type=int, default=0, help="Playback card index for default output")
    parser.add_argument("--playback-device", type=int, default=0, help="Playback device index for default output")
    args = parser.parse_args()

    if os.geteuid() != 0:
        raise SystemExit("This script must be run with sudo because it writes /etc/asound.conf")
    if args.capture_rate != 16000:
        raise SystemExit("capture_rate must remain 16000 for the wakeword/STT stack")

    print("Scanning ALSA capture devices via arecord -l ...")
    capture_dev = _find_capture_device(args.keyword)
    print(f"Using capture device: card {capture_dev.card}, device {capture_dev.device}, name={capture_dev.name}")

    content = _render_asound_conf(
        capture=capture_dev,
        capture_rate=args.capture_rate,
        playback_card=args.playback_card,
        playback_device=args.playback_device,
    )
    write_asound_conf(content)
    print("Done. Restart audio services or reboot for all processes to see the new default device.")


if __name__ == "__main__":
    main()
